using UnityEditor;
using UnityEngine;

namespace Game.EditorTools
{
    /// <summary>
    /// Import settings for the game's sound files in Assets/Resources/Audio (generated by Tools/SoundGen): music
    /// streams from disk (Vorbis), loops and effects are decompressed on load so they start instantly, effects are
    /// forced to mono (the game mixes everything 2D).
    /// </summary>
    public sealed class AudioImportSettings : AssetPostprocessor
    {
        const string Folder = "Assets/Resources/Audio/";

        void OnPreprocessAudio()
        {
            if (!assetPath.StartsWith(Folder)) return;
            var importer = (AudioImporter)assetImporter;
            bool music = System.IO.Path.GetFileNameWithoutExtension(assetPath) == "Music";
            importer.forceToMono = !music;
            importer.loadInBackground = music;
            AudioImporterSampleSettings s = importer.defaultSampleSettings;
            s.loadType = music ? AudioClipLoadType.Streaming : AudioClipLoadType.DecompressOnLoad;
            s.compressionFormat = AudioCompressionFormat.Vorbis;
            s.quality = music ? 0.7f : 0.85f;
            importer.defaultSampleSettings = s;
        }
    }
}
